receivers:
  otlp:
    protocols:
      grpc:
      http:
        cors_allowed_origins:
        - http://*
        - https://*

exporters:
  zipkin:
    endpoint: "http://zipkin-all-in-one:9411/api/v2/spans"

  jaeger:
    endpoint: jaeger-all-in-one:14250
    insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, jaeger]
      processors: [batch]
